#lang planet dyoo/simply-scheme:2
(define (switch sent)
  (se (switchFirst (first sent))
      (switchRest (bf sent))))
(define (switchFirst wd)
  (cond ((equal? wd 'You) 'I)
        ((equal? wd 'you) 'I)
        ((equal? wd 'I) 'You)
        ((equal? wd 'me) 'You)
        (else wd)) )
(define (switchRest sent)
  (if (empty? sent)
      '()
      (se (switchOne (first sent))
          (switchRest (butfirst sent)))))
(define (switchOne wd)
  (cond ((equal? wd 'you) 'me)
        ((equal? wd 'me) 'you)
        ((equal? wd 'I) 'you)
        (else wd) ))